# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.AddField(
            model_name='basket',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='producti', max_length=128, unique=True),
        ),
    ]
