# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='product',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
