# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20151204_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='num_stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='catalog',
            name='num_stars',
            field=models.IntegerField(default=1),
        ),
    ]
