# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20151204_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_namec', to='shop.Product'),
        ),
    ]
