# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20151205_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='namesC', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='basket',
            name='order',
        ),
    ]
